/**
 * @pkg/api-contracts — the ONE place both apps import their API from.
 *
 * Zero third-party runtime dependencies.  Just:
 *   • types generated by `openapi-typescript` from the committed `openapi.json`
 *   • a small hand-rolled fetch wrapper that consumes those types
 *
 * Rust (source of truth)
 *   #[utoipa::path] + #[derive(ToSchema)]                  ─┐
 *                                                            │  cargo run --bin export-openapi
 *   packages/api-contracts/openapi.json         (committed) ◄┘
 *                                                            │  openapi-typescript
 *   packages/api-contracts/src/generated/types.ts (git-ignored, produced at postinstall)
 *                                                            │  imported by
 *   this file → { api, configureApi }                       ─┘
 *                                                            │  used by
 *   apps/{customer,worker}/src/**
 *
 * Usage:
 *
 *     import { api, configureApi } from '@pkg/api-contracts';
 *
 *     configureApi({ baseUrl: 'http://192.168.0.5:3000' });
 *     const health = await api.health();
 *     const upd    = await api.checkUpdate({ current: 'v0.1', app: 'customer' });
 */

import type { paths, components } from './generated/types';

// ---------------------------------------------------------------------------
// Public schema re-exports — apps can type their state off these.
// ---------------------------------------------------------------------------

export type Schemas = components['schemas'];
export type HealthResponse      = Schemas['HealthResponse'];
export type CheckUpdateResponse = Schemas['CheckUpdateResponse'];

// ---------------------------------------------------------------------------
// Runtime config
// ---------------------------------------------------------------------------

export interface ApiConfig {
    /** Base URL of the API server, e.g. `http://192.168.0.5:3000`. */
    baseUrl: string;
    /** Extra headers attached to every request. */
    headers?: Record<string, string>;
    /** Optional custom fetch (interceptors, auth, logging). */
    fetch?: typeof fetch;
}

let config: ApiConfig = { baseUrl: 'http://localhost:3000' };

export function configureApi(patch: Partial<ApiConfig>): void {
    config = { ...config, ...patch };
}

export function getApiConfig(): Readonly<ApiConfig> {
    return config;
}

// ---------------------------------------------------------------------------
// Tiny fetch wrapper — deliberately untyped in the internals so callers
// can layer their own precise types on top (see `api` below).  This keeps
// the generic magic to a minimum and avoids the `unknown` inference trap
// that comes from indexing `paths[P][M]['responses'][200]…` through
// unresolved generics.
// ---------------------------------------------------------------------------

async function request<TResponse>(
    method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE',
    path: string,
    query?: Record<string, unknown>,
): Promise<TResponse> {
    const url = new URL(path, config.baseUrl);
    if (query) {
        for (const [k, v] of Object.entries(query)) {
            if (v !== undefined && v !== null) url.searchParams.set(k, String(v));
        }
    }
    const doFetch = config.fetch ?? fetch;
    const res = await doFetch(url.toString(), {
        method,
        headers: {
            accept: 'application/json',
            ...(config.headers ?? {}),
        },
    });
    if (!res.ok) {
        throw new Error(`${method} ${path} → ${res.status} ${res.statusText}`);
    }
    return res.json() as Promise<TResponse>;
}

// ---------------------------------------------------------------------------
// The typed API surface — one entry per endpoint.
// ---------------------------------------------------------------------------
//
// Each entry pins its response type to the generated `paths[…]` shape,
// so consumers get exact types without any generic gymnastics.
//
// Adding a new endpoint = one line.  If you get the URL wrong, the
// `paths['…']` index will be `never` and TS will error at build time.

type HealthOk       = paths['/health']['get']['responses'][200]['content']['application/json'];
type CheckUpdateOk  = paths['/api/check-update']['get']['responses'][200]['content']['application/json'];
type CheckUpdateQ   = NonNullable<paths['/api/check-update']['get']['parameters']['query']>;

export const api = {
    /** Liveness probe. */
    health: (): Promise<HealthOk> =>
        request<HealthOk>('GET', '/health'),

    /** Ask whether a newer OTA bundle exists for the given app + version. */
    checkUpdate: (query: CheckUpdateQ): Promise<CheckUpdateOk> =>
        request<CheckUpdateOk>('GET', '/api/check-update', query),
};
