/**
 * @pkg/api-contracts — the ONE place both apps import their API from.
 *
 * Zero third-party runtime dependencies.  Just:
 *   • types generated by `openapi-typescript` from the committed `openapi.json`
 *   • a ~40-line hand-rolled fetch wrapper that consumes those types
 *
 * Rust (source of truth)
 *   #[utoipa::path] + #[derive(ToSchema)]                  ─┐
 *                                                            │  cargo run --bin export-openapi
 *   packages/api-contracts/openapi.json         (committed) ◄┘
 *                                                            │  openapi-typescript
 *   packages/api-contracts/src/generated/types.ts (git-ignored, produced at postinstall)
 *                                                            │  imported by
 *   this file → { api, configureApi }                       ─┘
 *                                                            │  used by
 *   apps/{customer,worker}/src/**
 *
 * Usage:
 *
 *     import { api, configureApi } from '@pkg/api-contracts';
 *
 *     configureApi({ baseUrl: 'http://192.168.0.5:3000' });
 *     const health = await api.health();
 *     const upd    = await api.checkUpdate({ current: 'v0.1', app: 'customer' });
 */

import type { paths, components } from './generated/types';

// ---------------------------------------------------------------------------
// Public schema re-exports — apps can type their state off these.
// ---------------------------------------------------------------------------

export type Schemas = components['schemas'];
export type HealthResponse      = Schemas['HealthResponse'];
export type CheckUpdateResponse = Schemas['CheckUpdateResponse'];

// ---------------------------------------------------------------------------
// Runtime config
// ---------------------------------------------------------------------------

export interface ApiConfig {
    /** Base URL of the API server, e.g. `http://192.168.0.5:3000`. */
    baseUrl: string;
    /** Extra headers attached to every request. */
    headers?: Record<string, string>;
    /** Optional custom fetch (interceptors, auth, logging). */
    fetch?: typeof fetch;
}

let config: ApiConfig = { baseUrl: 'http://localhost:3000' };

export function configureApi(patch: Partial<ApiConfig>): void {
    config = { ...config, ...patch };
}

export function getApiConfig(): Readonly<ApiConfig> {
    return config;
}

// ---------------------------------------------------------------------------
// Tiny type-safe fetch wrapper
// ---------------------------------------------------------------------------

type QueryOf<P extends keyof paths, M extends keyof paths[P]> =
    paths[P][M] extends { parameters: { query?: infer Q } } ? Q : undefined;

type ResponseOf<P extends keyof paths, M extends keyof paths[P]> =
    paths[P][M] extends {
        responses: { 200: { content: { 'application/json': infer R } } };
    } ? R : never;

async function request<P extends keyof paths, M extends keyof paths[P] & string>(
    method: M,
    path: P,
    query?: QueryOf<P, M>,
): Promise<ResponseOf<P, M>> {
    const url = new URL(String(path), config.baseUrl);
    if (query) {
        for (const [k, v] of Object.entries(query as Record<string, unknown>)) {
            if (v !== undefined && v !== null) url.searchParams.set(k, String(v));
        }
    }
    const doFetch = config.fetch ?? fetch;
    const res = await doFetch(url.toString(), {
        method: method.toUpperCase(),
        headers: {
            accept: 'application/json',
            ...(config.headers ?? {}),
        },
    });
    if (!res.ok) {
        throw new Error(`${method.toUpperCase()} ${path} → ${res.status} ${res.statusText}`);
    }
    return res.json() as Promise<ResponseOf<P, M>>;
}

// ---------------------------------------------------------------------------
// The typed API surface — one entry per endpoint.
// ---------------------------------------------------------------------------
//
// Adding a new endpoint = one line here.  TS enforces the URL exists in
// `openapi.json` and infers request/response shapes automatically.

export const api = {
    /** Liveness probe. */
    health: () =>
        request('get', '/health'),

    /** Ask whether a newer OTA bundle exists for the given app + version. */
    checkUpdate: (query: QueryOf<'/api/check-update', 'get'>) =>
        request('get', '/api/check-update', query),
};
