#!/usr/bin/env bash
# ------------------------------------------------------------------
# DailyGig / TaskFinder — one-shot dev helper for macOS + zsh
# ------------------------------------------------------------------
# Usage:
#   ./scripts/dev.sh                # build + sync + OTA bundle (default)
#   ./scripts/dev.sh run            # build + sync + install + launch on device/emulator
#   ./scripts/dev.sh ota            # only build the OTA bundle (for hot-update)
#   ./scripts/dev.sh sync           # only vue build + cap sync (no OTA, no run)
#   ./scripts/dev.sh clean          # uninstall app + clear OTA cache + fresh sync
#   ./scripts/dev.sh server         # start the Axum OTA server
#   ./scripts/dev.sh doctor         # print environment & versions
#
# Safe to run from:
#   * a normal terminal (zsh / bash)
#   * Android Studio → Terminal tab (same shell)
# ------------------------------------------------------------------

set -euo pipefail

# --- Resolve project root (works no matter where the script is called from)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

APP_ID="com.yourcompany.taskfinder"
SERVER_PORT="3000"
BUNDLES_DIR="$ROOT_DIR/bundles"
CONFIG_FILE="$ROOT_DIR/.devrc"

# ---- Config helpers -----------------------------------------------------
# The script asks for OTA_HOST / OTA_PORT the first time and remembers the
# answer in .devrc so subsequent runs don't prompt.
# Precedence:
#   1. Env var already set (e.g.  OTA_HOST=1.2.3.4 ./scripts/dev.sh ota)
#   2. Value cached in .devrc
#   3. Interactive prompt with defaults

# Try to auto-detect a sensible default LAN IP (macOS / Linux)
detect_lan_ip() {
  local ip=""
  if [[ "$(uname)" == "Darwin" ]]; then
    ip="$(ipconfig getifaddr en0 2>/dev/null)"
    [[ -z "$ip" ]] && ip="$(ipconfig getifaddr en1 2>/dev/null)"
  fi
  if [[ -z "$ip" ]]; then
    ip="$(ifconfig 2>/dev/null | awk '/inet / && $2 !~ /^127\./ {print $2; exit}')"
  fi
  [[ -z "$ip" ]] && ip="192.168.0.4"
  printf "%s" "$ip"
}

# Load previously cached answers, if any
if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

save_config() {
  {
    echo "# Generated by scripts/dev.sh — safe to edit or delete"
    echo "OTA_HOST=\"$OTA_HOST\""
    echo "OTA_PORT=\"$OTA_PORT\""
  } > "$CONFIG_FILE"
}

# Ask the user with a default. Returns the answer on stdout.
# Args: prompt, default
ask() {
  local prompt="$1"
  local default="$2"
  local answer=""
  # Print prompt to stderr so command substitution captures only the value
  printf "%s [%s]: " "$prompt" "$default" >&2
  # -r: don't mangle backslashes.  Works in both bash and zsh.
  IFS= read -r answer </dev/tty || true
  [[ -z "$answer" ]] && answer="$default"
  printf "%s" "$answer"
}

# Prompt only when we actually need OTA config (server / ota / sync / run).
# Skips prompts for `doctor`, `help`, etc.
ensure_ota_config() {
  local changed=0
  if [[ -z "${OTA_HOST:-}" ]]; then
    OTA_HOST="$(ask 'Server LAN host/IP' "$(detect_lan_ip)")"
    changed=1
  fi
  if [[ -z "${OTA_PORT:-}" ]]; then
    OTA_PORT="$(ask 'Server port' "$SERVER_PORT")"
    changed=1
  fi
  export OTA_HOST OTA_PORT
  [[ $changed -eq 1 ]] && save_config
  printf "${DIM}   Using OTA server: http://%s:%s${RESET}\n" "$OTA_HOST" "$OTA_PORT" >&2
}

# --- Pretty logging ------------------------------------------------
if [[ -t 1 ]]; then
  BOLD="\033[1m"; DIM="\033[2m"; RED="\033[31m"; GREEN="\033[32m"
  YELLOW="\033[33m"; BLUE="\033[34m"; RESET="\033[0m"
else
  BOLD=""; DIM=""; RED=""; GREEN=""; YELLOW=""; BLUE=""; RESET=""
fi
log()  { printf "${BLUE}▶${RESET} %s\n" "$*"; }
ok()   { printf "${GREEN}✓${RESET} %s\n" "$*"; }
warn() { printf "${YELLOW}!${RESET} %s\n" "$*"; }
err()  { printf "${RED}✗${RESET} %s\n" "$*" >&2; }
step() { printf "\n${BOLD}== %s ==${RESET}\n" "$*"; }

# --- Guardrails ----------------------------------------------------
need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    err "Missing required command: $1"
    exit 1
  fi
}

ensure_deps() {
  need node
  need npm
  need npx
  if [[ ! -d node_modules ]]; then
    log "node_modules missing — running: npm install"
    npm install
  fi
}

is_server_up() {
  # Return 0 if the Axum OTA server responds on localhost
  if command -v curl >/dev/null 2>&1; then
    curl -sf "http://localhost:${SERVER_PORT}/health" >/dev/null 2>&1
  else
    return 1
  fi
}

# --- Commands ------------------------------------------------------

cmd_build_web() {
  ensure_ota_config
  step "Building Vue app (OTA_HOST=$OTA_HOST OTA_PORT=$OTA_PORT)"
  npm run build
  ok "dist/ rebuilt"
}

cmd_sync() {
  cmd_build_web
  step "Syncing Capacitor → Android"
  npx cap sync android
  ok "android/app/src/main/assets/public updated"
}

cmd_ota() {
  ensure_ota_config
  step "Building versioned OTA bundle (OTA_HOST=$OTA_HOST)"
  npm run bundle:ota
  if is_server_up; then
    ok "Axum server is up — new bundle is now live at http://localhost:${SERVER_PORT}"
    printf "${DIM}   The running app will pick it up within ~15s (auto-poll).${RESET}\n"
  else
    warn "Axum server is not running. Start it with:  ./scripts/dev.sh server"
  fi
  # Show what we produced
  if [[ -f "$BUNDLES_DIR/latest.json" ]]; then
    echo
    printf "${DIM}latest.json:${RESET}\n"
    cat "$BUNDLES_DIR/latest.json"
    echo
  fi
}

cmd_run() {
  cmd_sync
  step "Installing & launching on connected device / emulator"
  npx cap run android
}

cmd_clean() {
  step "Cleaning app install + OTA cache"
  if command -v adb >/dev/null 2>&1; then
    log "adb uninstall $APP_ID (ignore error if not installed)"
    adb uninstall "$APP_ID" || true
  else
    warn "adb not on PATH — skipping uninstall. Add \$ANDROID_HOME/platform-tools to PATH."
  fi
  cmd_sync
  ok "Clean slate. Now run:  ./scripts/dev.sh run"
}

cmd_server() {
  need cargo
  ensure_ota_config
  step "Starting Axum OTA server on 0.0.0.0:${OTA_PORT} (announcing http://${OTA_HOST}:${OTA_PORT})"
  cd "$ROOT_DIR/server"
  cargo run
}

cmd_config() {
  step "Reconfigure OTA server host/port"
  # Force re-prompt by clearing current values
  OTA_HOST=""
  OTA_PORT=""
  ensure_ota_config
  ok "Saved to $CONFIG_FILE"
}

cmd_doctor() {
  step "Environment"
  printf "  Node     : %s\n" "$(node -v 2>/dev/null || echo 'missing')"
  printf "  npm      : %s\n" "$(npm -v 2>/dev/null || echo 'missing')"
  printf "  Cargo    : %s\n" "$(cargo --version 2>/dev/null || echo 'missing')"
  printf "  adb      : %s\n" "$(adb --version 2>/dev/null | head -n1 || echo 'missing')"
  printf "  Java     : %s\n" "$(java -version 2>&1 | head -n1 || echo 'missing')"
  printf "  App ID   : %s\n" "$APP_ID"
  printf "  OTA host : %s:%s\n" "$OTA_HOST" "$OTA_PORT"
  printf "  Root     : %s\n" "$ROOT_DIR"

  step "This machine's LAN IPs (use one of these for OTA_HOST on your phone)"
  if command -v ipconfig >/dev/null 2>&1 && [[ "$(uname)" == "Darwin" ]]; then
    ipconfig getifaddr en0 2>/dev/null && true
    ipconfig getifaddr en1 2>/dev/null && true
  fi
  ifconfig 2>/dev/null | awk '/inet / && $2 != "127.0.0.1" {print "  " $2}' | sort -u

  step "Server"
  if is_server_up; then
    ok "Axum server responding on http://localhost:${SERVER_PORT}"
    curl -s "http://localhost:${SERVER_PORT}/health" || true
    echo
  else
    warn "Axum server not running (start with:  ./scripts/dev.sh server)"
  fi

  step "Devices"
  if command -v adb >/dev/null 2>&1; then
    adb devices
  else
    warn "adb missing"
  fi
}

usage() {
  cat <<EOF
${BOLD}DailyGig dev script${RESET}

Usage: ./scripts/dev.sh <command>

Commands:
  ${BOLD}run${RESET}      Build web + cap sync + install & launch on device (like ▶ in Studio)
  ${BOLD}sync${RESET}     Build web + cap sync (no launch)         ← use before pressing ▶ in Studio
  ${BOLD}ota${RESET}      Build a NEW versioned OTA bundle in ./bundles (hot-update)
  ${BOLD}clean${RESET}    Uninstall app + wipe OTA cache + fresh sync (fixes "old UI showing")
  ${BOLD}server${RESET}   Start the Axum OTA server (prompts for host/port on first run)
  ${BOLD}config${RESET}   Re-prompt for the LAN host/port (saved to .devrc)
  ${BOLD}doctor${RESET}   Print environment info

The first time you run sync/ota/run/server the script asks for:
  * Server LAN host/IP  (auto-detected, e.g. $(detect_lan_ip))
  * Server port         (default $SERVER_PORT)
…and remembers the answers in ${DIM}$CONFIG_FILE${RESET}.
Override any run with:   OTA_HOST=1.2.3.4 ./scripts/dev.sh ota

Default (no arg) = ${BOLD}sync + ota${RESET}   (safe: doesn't touch the device)
EOF
}

# --- Dispatch ------------------------------------------------------
ensure_deps

case "${1:-default}" in
  run)     cmd_run ;;
  sync)    cmd_sync ;;
  ota)     cmd_ota ;;
  clean)   cmd_clean ;;
  server)  cmd_server ;;
  config)  cmd_config ;;
  doctor)  cmd_doctor ;;
  default) cmd_sync; cmd_ota ;;
  -h|--help|help) usage ;;
  *) err "Unknown command: $1"; echo; usage; exit 1 ;;
esac
